# Generated by Django 5.2.1 on 2025-05-28 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('shifts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='last_change_by',
            field=models.ForeignKey(blank=True, help_text='The last person to change the state of the change request.', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='position',
            field=models.ForeignKey(blank=True, help_text='The position assosiated with this request.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.positions'),
        ),
        migrations.AddField(
            model_name='droprequest',
            name='last_change_by',
            field=models.ForeignKey(blank=True, help_text='The last person to change the state of the drop request.', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringshift',
            name='building',
            field=models.ForeignKey(help_text='The building the recurring shift is in.', on_delete=django.db.models.deletion.RESTRICT, to='core.buildings'),
        ),
        migrations.AddField(
            model_name='recurringshift',
            name='class_time',
            field=models.ForeignKey(blank=True, help_text='The class time that this recurring shift is for.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.classtimes'),
        ),
        migrations.AddField(
            model_name='recurringshift',
            name='position',
            field=models.ForeignKey(help_text='The position that this recurring shift is for.', on_delete=django.db.models.deletion.CASCADE, to='users.positions'),
        ),
        migrations.AddField(
            model_name='shift',
            name='building',
            field=models.ForeignKey(help_text='The building the shift is in.', on_delete=django.db.models.deletion.RESTRICT, to='core.buildings'),
        ),
        migrations.AddField(
            model_name='shift',
            name='position',
            field=models.ForeignKey(help_text='The position that this shift is for.', on_delete=django.db.models.deletion.CASCADE, to='users.positions'),
        ),
        migrations.AddField(
            model_name='shift',
            name='recurring_shift',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.recurringshift'),
        ),
        migrations.AddField(
            model_name='droprequest',
            name='shift',
            field=models.ForeignKey(help_text='The shift that this drop request is for.', on_delete=django.db.models.deletion.RESTRICT, to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='The shift that this change request is for.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='shift',
            field=models.OneToOneField(help_text='The shift that this attendance info is for.', on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_info', to='shifts.shift'),
        ),
    ]
