# Generated by Django 5.0.1 on 2024-01-28 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfo',
            name='shift',
            field=models.OneToOneField(help_text='The shift that this attendance info is for.', on_delete=django.db.models.deletion.RESTRICT, to='shifts.shift'),
        ),
        migrations.CreateModel(
            name='DropRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='The reason for the drop request.')),
                ('state', models.CharField(choices=[('Not Viewed', 'Not Viewed'), ('In Progress', 'In Progress'), ('Denied', 'Denied'), ('Approved', 'Approved')], help_text='The state of the drop request.', max_length=15)),
                ('last_changed_on', models.DateTimeField(blank=True, help_text='The date/time the drop request was last changed.', null=True)),
                ('last_change_by', models.ForeignKey(blank=True, help_text='The last person to change the state of the drop request.', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(help_text='The shift that this drop request is for.', on_delete=django.db.models.deletion.RESTRICT, to='shifts.shift')),
            ],
        ),
    ]
