# Generated by Django 5.0.1 on 2024-01-29 03:32

import shifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_alter_attendanceinfo_shift_droprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringshift',
            name='document',
            field=models.FileField(blank=True, help_text='Any attached document for the recurring shift. This will be copied to all shifts.', null=True, upload_to=shifts.models.recurring_shift_directory_path),
        ),
        migrations.AlterField(
            model_name='shift',
            name='document',
            field=models.FileField(blank=True, help_text='Any attached document for the shift.', null=True, upload_to=shifts.models.shift_directory_path),
        ),
    ]
