# Generated by Django 5.0.1 on 2024-01-31 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_classtimes_start_time'),
        ('shifts', '0003_alter_recurringshift_document_alter_shift_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringshift',
            name='class_time',
            field=models.ForeignKey(blank=True, help_text='The class time that this recurring shift is for.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.classtimes'),
        ),
    ]
