# Generated by Django 5.0.1 on 2024-02-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_recurringshift_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfo',
            name='shift',
            field=models.OneToOneField(help_text='The shift that this attendance info is for.', on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_info', to='shifts.shift'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='The shift that this change request is for.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='shifts.shift'),
        ),
    ]
