# Generated by Django 5.0.1 on 2024-02-05 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_attendanceinfo_shift_alter_changerequest_shift'),
        ('users', '0005_alter_positions_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='position',
            field=models.ForeignKey(blank=True, help_text='The position assosiated with this request.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.positions'),
        ),
    ]
