# Generated by Django 5.0.1 on 2024-02-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_changerequest_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='changed',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='require_punch_in_out',
            field=models.BooleanField(default=False, help_text='Whether or not the shift requires punch in/out.'),
        ),
    ]
