# Generated by Django 5.0.1 on 2025-02-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_remove_shift_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='original_duration',
            field=models.DurationField(default=None, help_text='The original duration of the shift.', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='original_start',
            field=models.DateTimeField(default=None, help_text='The start orignial date/time of the shift.', null=True),
        ),
    ]
