# Generated by Django 5.0.1 on 2024-01-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_semester_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayswitch',
            name='date',
            field=models.DateField(help_text='The date of the day switch. This date will act as "day to follow" for recurring shifts.', unique=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(help_text='The date of the holiday. All shifts on this date will be cancelled.', unique=True),
        ),
    ]
