# Generated by Django 5.0.1 on 2024-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_course_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtimes',
            name='time',
        ),
        migrations.AddField(
            model_name='classtimes',
            name='start_time',
            field=models.TimeField(default='00:00', help_text='The time class starts.'),
        ),
    ]
