# Generated by Django 5.0.1 on 2024-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_classtimes_time_classtimes_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimes',
            name='start_time',
            field=models.TimeField(help_text='The time class starts.'),
        ),
    ]
