# Generated by Django 5.0.1 on 2024-01-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_classtimes_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimes',
            name='start_time',
            field=models.TimeField(help_text='The time class starts. <b>Note:</b> <i>The time you specify is interpreted according to Amherst time. Therefore, regardless of your current timezone, please provide the time in accordance with Amherst time</i>.'),
        ),
    ]
