services:
  postgres:
    container_name: postgres-nexus
    image: postgres:latest
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    networks:
      - nexus-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    container_name: es-nexus
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    env_file:
      - ./.env.dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=es-nexus
      - cluster.name=es-docker-cluster
      - network.host=0.0.0.0
    expose:
      - "9200"
    networks:
      - nexus-network
    mem_limit: 4gb
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  django:
    container_name: django-nexus
    build: ./nexus
    volumes:
      - ./nexus:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - elasticsearch
    networks:
      - nexus-network
  
volumes:
  elasticsearch_data:
    driver: local
  postgres_data:
    driver: local

networks:
  nexus-network:
    driver: bridge