services:
  elasticsearch:
    container_name: es-nexus
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    env_file:
      - ./.env.prod
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms8g -Xmx8g
      - node.name=es-nexus
      - cluster.name=es-docker-cluster
      - network.host=0.0.0.0
    expose:
      - 9200
    networks:
      - nexus-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  django:
    container_name: django-nexus
    build:
      context: ./nexus
      dockerfile: Dockerfile.prod
    command: gunicorn nexus.wsgi:application --bind 0.0.0.0:8000 --workers 8 --threads 2 --access-logfile /home/log/gunicorn/access.log --error-logfile /home/log/gunicorn/error.log
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nexus/database.sqlite3:/home/app/web/database.sqlite3
      - ./gunicorn_logs:/home/log/gunicorn
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - elasticsearch
    networks:
      - nexus-network

  nginx-proxy:
    container_name: nginx-nexus
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - django
    networks:
      - nexus-network

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - nexus-network

volumes:
  elasticsearch_data:
  static_volume:
  certs:
  html:
  vhost:
  acme:

networks:
  nexus-network:
    driver: bridge