# Generated by Django 5.0.1 on 2024-01-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_positiongroups_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_end', models.DateField(help_text='The end date of the payroll week.')),
                ('status', models.CharField(choices=[('Not In HR', 'Not In Hr'), ('In HR On Time', 'In Hr On Time'), ('In HR Via Late Pay', 'In Hr Via Late Pay')], help_text='The status of the payroll.', max_length=30)),
                ('position', models.ForeignKey(help_text='The position that this payroll is for.', on_delete=django.db.models.deletion.RESTRICT, to='users.positions')),
            ],
            options={
                'unique_together': {('position', 'week_end')},
            },
        ),
        migrations.CreateModel(
            name='PayrollInHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_hours', models.DurationField(help_text='The total number of hours worked on Sunday.')),
                ('monday_hours', models.DurationField(help_text='The total number of hours worked on Monday.')),
                ('tuesday_hours', models.DurationField(help_text='The total number of hours worked on Tuesday.')),
                ('wednesday_hours', models.DurationField(help_text='The total number of hours worked on Wednesday.')),
                ('thursday_hours', models.DurationField(help_text='The total number of hours worked on Thursday.')),
                ('friday_hours', models.DurationField(help_text='The total number of hours worked on Friday.')),
                ('saturday_hours', models.DurationField(help_text='The total number of hours worked on Saturday.')),
                ('total_hours', models.DurationField(help_text='The total number of hours worked for the week.')),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollInHRViaLatePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_hours', models.DurationField(help_text='The total number of hours worked on Sunday.')),
                ('monday_hours', models.DurationField(help_text='The total number of hours worked on Monday.')),
                ('tuesday_hours', models.DurationField(help_text='The total number of hours worked on Tuesday.')),
                ('wednesday_hours', models.DurationField(help_text='The total number of hours worked on Wednesday.')),
                ('thursday_hours', models.DurationField(help_text='The total number of hours worked on Thursday.')),
                ('friday_hours', models.DurationField(help_text='The total number of hours worked on Friday.')),
                ('saturday_hours', models.DurationField(help_text='The total number of hours worked on Saturday.')),
                ('total_hours', models.DurationField(help_text='The total number of hours worked for the week.')),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollNotInHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_hours', models.DurationField(help_text='The total number of hours worked on Sunday.')),
                ('monday_hours', models.DurationField(help_text='The total number of hours worked on Monday.')),
                ('tuesday_hours', models.DurationField(help_text='The total number of hours worked on Tuesday.')),
                ('wednesday_hours', models.DurationField(help_text='The total number of hours worked on Wednesday.')),
                ('thursday_hours', models.DurationField(help_text='The total number of hours worked on Thursday.')),
                ('friday_hours', models.DurationField(help_text='The total number of hours worked on Friday.')),
                ('saturday_hours', models.DurationField(help_text='The total number of hours worked on Saturday.')),
                ('total_hours', models.DurationField(help_text='The total number of hours worked for the week.')),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollNotSigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_hours', models.DurationField(help_text='The total number of hours worked on Sunday.')),
                ('monday_hours', models.DurationField(help_text='The total number of hours worked on Monday.')),
                ('tuesday_hours', models.DurationField(help_text='The total number of hours worked on Tuesday.')),
                ('wednesday_hours', models.DurationField(help_text='The total number of hours worked on Wednesday.')),
                ('thursday_hours', models.DurationField(help_text='The total number of hours worked on Thursday.')),
                ('friday_hours', models.DurationField(help_text='The total number of hours worked on Friday.')),
                ('saturday_hours', models.DurationField(help_text='The total number of hours worked on Saturday.')),
                ('total_hours', models.DurationField(help_text='The total number of hours worked for the week.')),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payroll')),
            ],
        ),
    ]
