# Generated by Django 5.2.1 on 2025-05-28 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_end', models.DateField(help_text='The end date of the payroll week.')),
                ('status', models.CharField(choices=[('Not In HR', 'Not In Hr'), ('In HR On Time', 'In Hr On Time'), ('In HR Via Late Pay', 'In Hr Via Late Pay')], help_text='The status of the payroll.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollInHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Sunday.')),
                ('monday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Monday.')),
                ('tuesday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Tuesday.')),
                ('wednesday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Wednesday.')),
                ('thursday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Thursday.')),
                ('friday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Friday.')),
                ('saturday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Saturday.')),
                ('total_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked for the week.')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollInHRViaLatePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Sunday.')),
                ('monday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Monday.')),
                ('tuesday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Tuesday.')),
                ('wednesday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Wednesday.')),
                ('thursday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Thursday.')),
                ('friday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Friday.')),
                ('saturday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Saturday.')),
                ('total_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked for the week.')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollNotInHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Sunday.')),
                ('monday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Monday.')),
                ('tuesday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Tuesday.')),
                ('wednesday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Wednesday.')),
                ('thursday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Thursday.')),
                ('friday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Friday.')),
                ('saturday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Saturday.')),
                ('total_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked for the week.')),
                ('approved_by_user', models.BooleanField(default=False, help_text='Whether the user has approved the hours.')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollNotSigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Sunday.')),
                ('monday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Monday.')),
                ('tuesday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Tuesday.')),
                ('wednesday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Wednesday.')),
                ('thursday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Thursday.')),
                ('friday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Friday.')),
                ('saturday_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Saturday.')),
                ('total_hours', models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked for the week.')),
            ],
        ),
    ]
