# Generated by Django 5.2.1 on 2025-05-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payrolls', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='position',
            field=models.ForeignKey(help_text='The position that this payroll is for.', on_delete=django.db.models.deletion.RESTRICT, to='users.positions'),
        ),
        migrations.AddField(
            model_name='payrollinhr',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='in_hr', to='payrolls.payroll'),
        ),
        migrations.AddField(
            model_name='payrollinhrvialatepay',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_pay', to='payrolls.payroll'),
        ),
        migrations.AddField(
            model_name='payrollnotinhr',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='not_in_hr', to='payrolls.payroll'),
        ),
        migrations.AddField(
            model_name='payrollnotsigned',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='not_signed', to='payrolls.payroll'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('position', 'week_end')},
        ),
    ]
