# Generated by Django 5.0.1 on 2024-01-29 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollinhr',
            name='friday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Friday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhr',
            name='monday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Monday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhr',
            name='saturday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Saturday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhr',
            name='sunday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Sunday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhr',
            name='thursday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Thursday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhr',
            name='total_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked for the week.'),
        ),
        migrations.AlterField(
            model_name='payrollinhr',
            name='tuesday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Tuesday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhr',
            name='wednesday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Wednesday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='friday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Friday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='monday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Monday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='saturday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Saturday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='sunday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Sunday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='thursday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Thursday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='total_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked for the week.'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='tuesday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Tuesday.'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='wednesday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Wednesday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='friday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Friday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='monday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Monday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='saturday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Saturday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='sunday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Sunday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='thursday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Thursday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='total_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked for the week.'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='tuesday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Tuesday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='wednesday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Wednesday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='friday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Friday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='monday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Monday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='saturday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Saturday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='sunday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Sunday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='thursday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Thursday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='total_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked for the week.'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='tuesday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Tuesday.'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='wednesday_hours',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The total number of hours worked on Wednesday.'),
        ),
    ]
