# Generated by Django 5.0.1 on 2024-02-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0002_alter_payrollinhr_friday_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollinhr',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='in_hr', to='payrolls.payroll'),
        ),
        migrations.AlterField(
            model_name='payrollinhrvialatepay',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_pay', to='payrolls.payroll'),
        ),
        migrations.AlterField(
            model_name='payrollnotinhr',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='not_in_hr', to='payrolls.payroll'),
        ),
        migrations.AlterField(
            model_name='payrollnotsigned',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='not_signed', to='payrolls.payroll'),
        ),
    ]
