# Generated by Django 5.0.1 on 2024-06-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0003_alter_payrollinhr_payroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollnotinhr',
            name='approved_by_user',
            field=models.BooleanField(default=False, help_text='Whether the user has approved the hours.'),
        ),
    ]
