# Generated by Django 5.2.1 on 2025-05-28 23:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_status', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_level', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.faculty')),
                ('personal_website', models.URLField(blank=True, max_length=500, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_website', models.URLField(blank=True, max_length=500, null=True)),
                ('research_outline', models.TextField(blank=True, null=True)),
                ('miscellaneous', models.TextField(blank=True, null=True)),
                ('allowed_to_post_oportunities', models.BooleanField(default=False)),
                ('subjects', models.ManyToManyField(blank=True, to='core.coursesubject')),
                ('positions', models.ManyToManyField(blank=True, to='ours.facultyposition')),
                ('keywords', models.ManyToManyField(blank=True, to='ours.keyword')),
            ],
            options={
                'ordering': ['faculty__last_name', 'faculty__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('on_campus', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(max_length=500, unique=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_for_credit', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('show_on_website', models.BooleanField(default=True)),
                ('show_on_website_start_date', models.DateField(default=datetime.date.today)),
                ('show_on_website_end_date', models.DateField(default=datetime.date(2099, 12, 31))),
                ('link_not_working', models.BooleanField(default=False)),
                ('link_not_working_override', models.BooleanField(default=False)),
                ('website_data', models.TextField(blank=True, default='', null=True)),
                ('featured', models.BooleanField(default=False)),
                ('keywords', models.ManyToManyField(blank=True, to='ours.keyword')),
                ('related_to_major', models.ManyToManyField(blank=True, to='ours.majors')),
                ('related_to_track', models.ManyToManyField(blank=True, to='ours.tracks')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MinGPARestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ours.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='MajorRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_be_all_majors', models.BooleanField(default=False)),
                ('majors', models.ManyToManyField(to='ours.majors')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ours.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOpportunityRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('criteria', models.CharField(max_length=255)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ours.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenshipRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_status', models.ManyToManyField(to='ours.citizenshipstatus')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ours.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='StudyLevelRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ours.opportunity')),
                ('study_level', models.ManyToManyField(to='ours.studylevel')),
            ],
        ),
    ]
