# Generated by Django 5.0.1 on 2024-04-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_classtimes_start_time'),
        ('ours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='keywords',
            field=models.ManyToManyField(to='ours.keyword'),
        ),
        migrations.AlterField(
            model_name='facultydetails',
            name='positions',
            field=models.ManyToManyField(blank=True, to='ours.facultyposition'),
        ),
        migrations.AlterField(
            model_name='facultydetails',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='core.coursesubject'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='ours.keyword'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='related_to_major',
            field=models.ManyToManyField(blank=True, to='ours.majors'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='related_to_track',
            field=models.ManyToManyField(blank=True, to='ours.tracks'),
        ),
    ]
