# Generated by Django 5.0.1 on 2024-05-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ours', '0003_alter_facultydetails_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultydetails',
            options={'ordering': ['faculty__last_name', 'faculty__first_name']},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
