# Generated by Django 5.0.1 on 2024-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ours', '0004_alter_facultydetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
