# Generated by Django 5.0.1 on 2024-05-28 23:58

import ours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ours', '0006_alter_opportunity_show_on_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='link_not_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='website_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.URLField(default=ours.models.url_for_page_not_found),
        ),
    ]
