# Generated by Django 5.0.1 on 2024-06-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ours', '0008_alter_opportunity_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['keyword']},
        ),
    ]
