# Generated by Django 5.0.1 on 2024-06-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ours', '0009_alter_keyword_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='link_not_working_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
