# Generated by Django 5.0.1 on 2024-06-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ours', '0010_opportunity_link_not_working_override_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['title']},
        ),
    ]
