# Generated by Django 5.0.1 on 2024-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ours', '0011_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
