# Generated by Django 5.0.1 on 2024-01-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_classtimes_start_time'),
        ('shifts', '0002_alter_attendanceinfo_shift_droprequest'),
        ('users', '0004_alter_positiongroups_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRoleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_courses', models.ManyToManyField(help_text='Courses that this role is for.', to='core.course')),
                ('position', models.OneToOneField(help_text='The position that this role is for.', on_delete=django.db.models.deletion.CASCADE, to='users.positions')),
            ],
        ),
        migrations.CreateModel(
            name='TutorShiftInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(help_text='The role that this shift info is for.', on_delete=django.db.models.deletion.RESTRICT, to='tutors.tutorroleinfo')),
                ('shift', models.OneToOneField(help_text='The shift that this shift info is for.', on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
            options={
                'unique_together': {('shift', 'role')},
            },
        ),
    ]
