# Generated by Django 5.2.1 on 2025-05-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRoleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_courses', models.ManyToManyField(help_text='Courses that this role is for.', to='core.course')),
            ],
        ),
    ]
