# Generated by Django 5.2.1 on 2025-05-27 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorroleinfo',
            name='position',
            field=models.OneToOneField(help_text='The position that this role is for.', on_delete=django.db.models.deletion.CASCADE, to='users.positions'),
        ),
    ]
