# Generated by Django 5.0.1 on 2024-02-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorShiftInfo',
        ),
    ]
