apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: nexus
spec:
  ports:
    - port: 8000
  selector:
    app: nexus
    tier: app
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  labels:
    app: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: nexus
spec:
  selector:
    matchLabels:
      app: nexus
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nexus
        tier: app
    spec:
      volumes:
        - name: django-data
          persistentVolumeClaim:
            claimName: django-pvc
      containers:
        - name: app
          image: nexus:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: django-data
              mountPath: /usr/src/app/
          env:
            - name: NEXUS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: NEXUS_SECRET_KEY
            - name: NEXUS_DEBUG
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: NEXUS_DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ALLOWED_HOSTS
            - name: ELASTICSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: ELASTICSEARCH_HOST
            - name: ELASTICSEARCH_PORT
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: ELASTICSEARCH_PORT
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: ELASTIC_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PORT
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8000
              name: django
        
        - name: proxy
          image: nginx:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - name: django-data
              mountPath: /usr/src/proxy/
          env:
            - name: APP_HOST
              value: "127.0.0.1"
            - name: APP_PORT
              value: "8000"
