# Generated by Django 5.0.1 on 2024-01-22 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(0, 'Tech'), (1, 'SI'), (2, 'Tutor'), (3, 'SI PM'), (4, 'Tutor PM'), (5, 'Group Tutor'), (6, 'OURS Mentor'), (7, 'Office Assistant')], help_text='The position the user has.')),
                ('hourly_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly pay for the position.', max_digits=5)),
                ('semester', models.ForeignKey(help_text='The semester position is for.', on_delete=django.db.models.deletion.RESTRICT, to='core.semester')),
                ('user', models.ForeignKey(help_text='User position is for.', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['semester', 'user__last_name', 'user__first_name', 'user__email', 'position'],
            },
        ),
    ]
