# Generated by Django 5.0.1 on 2024-01-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_positions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positions',
            unique_together={('semester', 'user', 'position')},
        ),
        migrations.CreateModel(
            name='PositionGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group.', max_length=100, unique=True)),
                ('members', models.ManyToManyField(help_text='Members of the group.', related_name='groups', to='users.positions')),
                ('semester', models.ForeignKey(help_text='The semester group is for.', on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
    ]
