# Generated by Django 5.0.1 on 2024-01-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_alter_positions_unique_together_positiongroups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiongroups',
            options={'ordering': ['semester', 'name']},
        ),
        migrations.AlterField(
            model_name='positiongroups',
            name='name',
            field=models.CharField(help_text='Name of the group.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='positiongroups',
            unique_together={('semester', 'name')},
        ),
    ]
