# Generated by Django 5.0.1 on 2024-01-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_positiongroups_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Tech'), (1, 'SI'), (2, 'Tutor'), (3, 'SI PM'), (4, 'Tutor PM'), (5, 'Group Tutor'), (6, 'OURS Mentor'), (7, 'Office Assistant'), (8, 'Office Assistant PM'), (9, 'OURS Mentor PM')], help_text='The position the user has.'),
        ),
    ]
