# Generated by Django 5.2.1 on 2025-05-27 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIRoleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_sections', models.BooleanField(default=False, help_text='If this role is for all sections of the class.')),
            ],
        ),
        migrations.CreateModel(
            name='SIReccuringShiftInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.classtimes')),
            ],
        ),
    ]
