# Generated by Django 5.0.1 on 2024-01-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_classtimes_start_time'),
        ('shifts', '0002_alter_attendanceinfo_shift_droprequest'),
        ('users', '0004_alter_positiongroups_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIRoleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_class', models.ForeignKey(help_text='The class that this role is for.', on_delete=django.db.models.deletion.RESTRICT, to='core.classes')),
                ('position', models.ForeignKey(help_text='The position that this role is for.', on_delete=django.db.models.deletion.RESTRICT, to='users.positions')),
            ],
            options={
                'unique_together': {('position', 'assigned_class')},
            },
        ),
        migrations.CreateModel(
            name='SIShiftInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(help_text='The role that this shift info is for.', on_delete=django.db.models.deletion.RESTRICT, to='SIs.siroleinfo')),
                ('shift', models.OneToOneField(help_text='The shift that this shift info is for.', on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
            options={
                'unique_together': {('shift', 'role')},
            },
        ),
    ]
