# Generated by Django 5.2.1 on 2025-05-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SIs', '0001_initial'),
        ('core', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sireccuringshiftinfo',
            name='recuring_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.recurringshift'),
        ),
        migrations.AddField(
            model_name='siroleinfo',
            name='assigned_class',
            field=models.ForeignKey(blank=True, help_text='The class that this role is for.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.classes'),
        ),
    ]
