# Generated by Django 5.2.1 on 2025-05-27 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SIs', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siroleinfo',
            name='position',
            field=models.ForeignKey(help_text='The position that this role is for.', on_delete=django.db.models.deletion.RESTRICT, to='users.positions'),
        ),
        migrations.AddField(
            model_name='sireccuringshiftinfo',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIs.siroleinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='siroleinfo',
            unique_together={('position', 'assigned_class')},
        ),
        migrations.AlterUniqueTogether(
            name='sireccuringshiftinfo',
            unique_together={('role', 'class_time')},
        ),
    ]
