# Generated by Django 5.0.1 on 2024-08-30 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIs', '0004_siroleinfo_all_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sireccuringshiftinfo',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIs.siroleinfo'),
        ),
    ]
